name: Android CI

on:
  push:
    branches:
    - master
    - tree/*MAINT

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: create gradle.properties
      run: echo 'org.gradle.jvmargs=-Xmx4096m' > gradle.properties
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew assembleCurrentDebug
    - name: Run lint
      run: ./gradlew lint
